Add files via upload
SwissTierrasColombia/Asistente-LADM-COL-docs pull request #22
Opened 2021-04-22 06:41 UTC by jonyfido

2021-04-22 06:42 UTC, jonyfido commented
imagenes para vizualizar las secciones del archivo MD.

2021-04-26 16:30 UTC, gacarrillor requested changes
Gracias por el PR (Pull Request) @jonyfido

Algunas sugerencias antes de aprobarlo:

 + [x] Los archivos `Cancelar_tarea.gif` y `Ver_tareas.gif` no tienen los íconos en el panel de tareas. Otros archivos como `tareas.png` si los tienen. No podemos subir archivos de imagen que no tengan los íconos correctamente cargados.

 + [x] El archivo `Tareas.png` no tiene un tamaño apropiado para la documentación, pues tiene 142x180 píxeles. Se sugiere tomarlo a un tamaño normal.

 + [ ] El archivo `Tarea0.png` muestra una secuencia. Se sugiere grabar un GIF para ilustrarla.

 + [ ] Se sugiere crear nuevo proyecto de QGIS (CTRL+N) antes de grabar los GIFs o capturar pantalla, para que no aparezcan anuncios propios de la comunidad QGIS en la región del mapa. Se prefiere blanco o con datos LADM-COL.

2021-06-25 14:02 UTC, jhonalex06 commented
> Gracias por el PR (Pull Request) @jonyfido
> 
> Algunas sugerencias antes de aprobarlo:
> 
> * [ ]  Los archivos `Cancelar_tarea.gif` y `Ver_tareas.gif` no tienen los íconos en el panel de tareas. Otros archivos como `tareas.png` si los tienen. No podemos subir archivos de imagen que no tengan los íconos correctamente cargados.
> * [ ]  El archivo `Tareas.png` no tiene un tamaño apropiado para la documentación, pues tiene 142x180 píxeles. Se sugiere tomarlo a un tamaño normal.
> * [ ]  El archivo `Tarea0.png` muestra una secuencia. Se sugiere grabar un GIF para ilustrarla.
> * [ ]  Se sugiere crear nuevo proyecto de QGIS (CTRL+N) antes de grabar los GIFs o capturar pantalla, para que no aparezcan anuncios propios de la comunidad QGIS en la región del mapa. Se prefiere blanco o con datos LADM-COL.

2021-06-25 14:08 UTC, jonyfido commented
> Gracias por el PR (Pull Request) @jonyfido
> 
> Algunas sugerencias antes de aprobarlo:
> 
> * [x]  Los archivos `Cancelar_tarea.gif` y `Ver_tareas.gif` no tienen los íconos en el panel de tareas. Otros archivos como `tareas.png` si los tienen. No podemos subir archivos de imagen que no tengan los íconos correctamente cargados.
> * [x]  El archivo `Tareas.png` no tiene un tamaño apropiado para la documentación, pues tiene 142x180 píxeles. Se sugiere tomarlo a un tamaño normal.
> * [x]  El archivo `Tarea0.png` muestra una secuencia. Se sugiere grabar un GIF para ilustrarla.
> * [x]  Se sugiere crear nuevo proyecto de QGIS (CTRL+N) antes de grabar los GIFs o capturar pantalla, para que no aparezcan anuncios propios de la comunidad QGIS en la región del mapa. Se prefiere blanco o con datos LADM-COL.

->Este Issue se soluciona en la PR (Pull Request) #20

2021-06-28 15:05 UTC, gacarrillor commented
> ->Este Issue se soluciona en la PR (Pull Request) #20

@jonyfido, ¿Entonces cerramos este PR?

2021-06-28 15:11 UTC, jhonalex06 commented
> > ->Este Issue se soluciona en la PR (Pull Request) #20
> 
> @jonyfido, ¿Entonces cerramos este PR?

Yo creería que si, ya las imágenes y el md están en el PR #20

2021-06-28 15:12 UTC, closed without merging