Update cargar_capas
SwissTierrasColombia/Asistente-LADM-COL-docs pull request #32
Opened 2021-05-10 16:46 UTC by jonyfido

Se actualiza la sección para revisión y ajustes.

2021-05-10 17:27 UTC, gacarrillor requested changes
En general veo bien esta sección @jonyfido. Dejo un par de comentarios entre líneas (es decir, en el código fuente de la documentación) y la siguiente sugerencia.

Le sugeriría si se puede agregar una subsección para explicar cómo usar los checkboxes del diálogo. Esto es, agregar un ejemplo de búsqueda de un dominio (primero, que no aparece porque la caja de chequeo está desactivada, luego activarla y ver cómo aparece y finalmente cargarla), de una asociación (ej. uebaunit) y de una estructura (ej. Archivo fuente).

Sugiero esto porque los usuarios (me pasó esta misma mañana dando un soporte) no conocen que hay capas del modelo que no aparecen listadas inicialmente porque son dominios, estructuras o asociaciones.

2021-05-10 17:27 UTC, gacarrillor commented on source/cargar_capas.md
> +Después de haber creado la estructura LADM-COL en la base de datos donde se guardarán los datos para probar las funciones del Asistente, y haber realizado la importación de estos a partir del archivo
Cuando tengamos enlaces internos, siempre mejor evitar rutas absolutas. 

En este caso, el enlace es interno y corresponde a otra sección de la documentación. Puede verse [aquí](https://raw.githubusercontent.com/SwissTierrasColombia/Asistente-LADM-COL-docs/master/source/configuracion.md) cómo referenciarlo.

Ejemplo: `[rol activo](introduccion.html#dialogo-de-bienvenida)`

2021-05-10 17:27 UTC, gacarrillor commented on source/cargar_capas.md
> +</div>
Esta parte merece un pantallazo con las opciones desplegadas.

2021-05-28 05:56 UTC, jonyfido commented on source/cargar_capas.md
> +Después de haber creado la estructura LADM-COL en la base de datos donde se guardarán los datos para probar las funciones del Asistente, y haber realizado la importación de estos a partir del archivo
Resuelto en 40c001051e96387bd403f093d5e6a58124690e11

2021-05-28 05:57 UTC, jonyfido commented on source/cargar_capas.md
> +</div>
Actualizado en 40c001051e96387bd403f093d5e6a58124690e11

2021-05-28 19:14 UTC, jonyfido commented on source/cargar_capas.md
> +</div>
Actualizado en 623bd8ea983dfde01d93c224d97c3231d0546b3a

2021-06-03 20:36 UTC, gacarrillor reviewed
Cuidado, al referirse a las capas como "datos", se confunde al lector.

Lo que cargamos a QGIS con capas/tablas, las cuales, a su vez tienen datos.

Todos los comentarios realizados en la revisión fueron ya corregidos (por el revisor). Se sugiere tener en cuenta estas sugerencias para el resto de Pull Requests abiertos!

2021-06-03 20:36 UTC, gacarrillor commented on source/cargar_capas.md
> +Es de tener en cuenta que los datos se muestran en grupos según al modelo núcleo o extendido del modelo LADM-COL en que están estructurados los datos, adicional a esto en la parte inferior de la vent
Cuidado, la visualización en HTML del **: ballot_box_with_check :** no es como se observa en GitHub. 

En HTML aparece así:

![image](https://user-images.githubusercontent.com/652785/120704429-3048d380-c47c-11eb-936b-b6e978b35364.png)

Lo cual difiere de lo que se quiere mostrar al usuario.

2021-06-03 20:36 UTC, gacarrillor commented on source/cargar_capas.md
> +<a class="" data-lightbox="Cajas de selección" href="_static/cargar_capas/Cajas_seleccion.png" title="Cajas de selección" data-title="Cajas de selección"><img src="_static/cargar_capas/Cajas_seleccio
Cuando queramos refereirnos a los widgets de tipo _check box_, siempre usaremos el término "Cajas de chequeo".

2021-06-03 20:36 UTC, gacarrillor commented on source/cargar_capas.md
> +* Mostrar asociaciones:  Muestra las tablas que almacenan relaciones entre tablas y capas geográficas de los modelos LADM-COL desplegados.
No hay necesidad de repetir tanto la frase... "de los modelos LADM-COL desplegados".

2021-06-03 20:36 UTC, gacarrillor commented on source/cargar_capas.md
> +Este permite cargar una o muchas capas configurando de forma automática los dominios, dependencias y relaciones del modelo, así como una simbología única para cada capa espacial que se cargue. Tambié
Este párrafo es un gran dadidato a ser presentaco como una caja de color, de tipo TIP. En general la sección quedó bastante cargada de texto, y las cajas de colores ayudan a amenizar la lectura.

2021-06-03 20:40 UTC, merged