Update exportar_importar_datos.md
SwissTierrasColombia/Asistente-LADM-COL-docs pull request #35
Opened 2021-05-11 12:31 UTC by Angel282

2021-07-02 15:56 UTC, gacarrillor requested changes
Reducir el tamaño de los GIFs, especialmente de 

cap12importexport7.gif 

No requerimos tener la ventana de QGIS tan grande pues estamos interesados en lo que ocurre en el proceso de importar/exportar. Si puede bajarse un poco la resolución mejor.

2021-07-02 16:15 UTC, jhonalex06 commented
> Reducir el tamaño de los GIFs, especialmente de
> 
> cap12importexport7.gif
> 
> No requerimos tener la ventana de QGIS tan grande pues estamos interesados en lo que ocurre en el proceso de importar/exportar. Si puede bajarse un poco la resolución mejor.

Listo, yo me encargo de editarlo para que reducir el tamaño

2021-07-19 19:54 UTC, gacarrillor requested changes
+ [x] Favor renombrar las imágenes y animaciones. Los nombres actuales (paso2.png) no son apropiados para ser integrados con el resto de imágenes/animaciones de la documentación, puesto que son demasiado ambiguos.

 + [ ] Adicionalmente, revisar esta sugerencia en todos los PRs abiertos: https://github.com/SwissTierrasColombia/Asistente-LADM-COL-docs/pull/34#pullrequestreview-708496280

En este PR ocurre también...
Como el título de las imágenes/animaciones se repite para exportar e importar datos, Sphinx se confunde y genera erróneamente una secuencia de GIFs como en la siguiennte imagen (ver la flecha hacia la derecha):

![image](https://user-images.githubusercontent.com/652785/125985578-4197490b-0012-4404-b9a7-913b9beaae98.png)

En este sentido, los títulos de imágenes/animaciones no deberían ser nombres genéricos (Paso3) sino títulos completos (Paso 3: Exportar XTF).

2021-07-26 17:05 UTC, gacarrillor approved these changes

2021-07-26 17:05 UTC, merged