Update gestion_de_insumos.md
SwissTierrasColombia/Asistente-LADM-COL-docs pull request #36
Opened 2021-05-11 15:47 UTC by Angel282

2021-08-02 17:01 UTC, gacarrillor requested changes
+ [ ] Revisar si es necesario crear un paso extra o por lo menos mencionar la selección de la BD, que es muy relevante en esta ETL. Tener en cuenta, por ejemplo, cuál es la conexión que aparece seleccionada por defecto para un usuario nuevo, que no ha utilizado nunca el Asistente LADM-COL.

2021-08-02 17:01 UTC, gacarrillor commented on source/tutorial/gestion_de_insumos.md
> +
Como se trata de un tutorial, hay que llevar de la mano al usuario. Indicar para qué se realiza la identificación de novedades en el contexto del tutorial.

2021-08-02 17:01 UTC, gacarrillor commented on source/tutorial/gestion_de_insumos.md
> +
La animación muestra que se seleccionó "Usar otra BD", pero en realidad se quiere usar la misma BD, como se indica en el párrafo. Ajustar el GIF.

2021-08-12 20:13 UTC, jhonalex06 commented on source/tutorial/gestion_de_insumos.md
> +
Solucionado en el commit a9b5d5d

2021-08-12 20:13 UTC, jhonalex06 commented on source/tutorial/gestion_de_insumos.md
> +
Solucionado en el commit a9b5d5d

2021-08-24 22:07 UTC, gacarrillor approved these changes

2021-08-24 22:07 UTC, merged