[Captura y estructuración de datos] Preprocesamiento de insumos
SwissTierrasColombia/Asistente-LADM-COL-docs pull request #39
Opened 2021-05-19 20:35 UTC by jhonalex06

- [ ] Creación de terrenos y sus relaciones
- [ ] Creación de construcciones
- [ ] Creación de unidades de construcción
- [ ] Verificación de imágenes

2021-05-25 15:00 UTC, gacarrillor commented
¿Faltaría sección de creación de Servidumbre de tránsito?

2021-05-25 15:16 UTC, jhonalex06 commented
> ¿Faltaría sección de creación de Servidumbre de tránsito?

Tienes razón, pero me surge la duda si tenemos datos para la creación de la servidumbre de tránsito, en caso de que no se tengan, tocaría generarlos.

2021-07-01 23:16 UTC, gacarrillor requested changes
Muchos comentarios.

Estas recomendaciones se deben tener en cuenta para las demás subsecciones que se elaboren.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<p>Para el caso de <b>area_construccion</b>, se utiliza la expresión <i>$area</i> ya que los datos iniciales no cuentan con información para este campo.</p>
Ajustar la expresión, según lo sugerido arriba.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Una vez que los terrenos han sido creados, es necesario calcular o en su defecto actualizar el área del terreno. Para ello, debes dar clic en el botón `Abrir tabla de atributos` ubicado en la parte s
> debes emplear la función *\$area*.

No es cierto, ver https://github.com/SwissTierrasColombia/Asistente-LADM-COL/issues/449

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +### Servidumbre de paso
Entiendo que ahora se denominan servidumbres de tránsito.
Ver https://github.com/SwissTierrasColombia/Asistente-LADM-COL/blob/a786b2d408a7de6c7f53ffa3c44466542c8fe510/asistente_ladm_col/resources/models/Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_0.ili#L2843

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +</ol>
No necesitamos HTML para hacer una lista numerada en Markdown. Pasarla a dicha sintaxis.

De hecho, así es como aparece desplegada según está definido en el PR:

![image](https://user-images.githubusercontent.com/652785/124195538-4acc9780-da90-11eb-85f3-c6b3e1d4e909.png)

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Posteriormente, das clic en la opción *"Seleccionar todos los linderos"* y luego en el botón `Finalizar`.
Cambiar por "das clic en EL BOTÓN *"Seleccionar todos los linderos"* y..."

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Posteriormente, das clic en la opción *"Seleccionar todos los linderos"* y luego en el botón `Finalizar`.
De nuevo el comentario del otro día: 

![image](https://user-images.githubusercontent.com/652785/124195889-e3631780-da90-11eb-9ac1-45ad084c8296.png)

Mejor unificar la forma en que se resaltan los nombres de los botones. En la imagen de arriba hay 2 formas diferentes muy seguidamente.

Se sugiere usar la forma del botón `Finalizar`.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +#### Paso 3: Cálculo área del terreno
Redacción: Cálculo del área del terreno

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Una vez que los terrenos han sido creados, es necesario calcular o en su defecto actualizar el área del terreno. Para ello, debes dar clic en el botón `Abrir tabla de atributos` ubicado en la parte s
No se a qué se refiere "en la parte superior de la barra de tareas".

Supongo se trata de las barras de herramientas, y mejor no hacer referencia a "la parte superior", pues los usuarios podrían haber desplazado esa toolbar para que quede vertical, perdiendo sentido la mención a "la parte superior".

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 3: Cálculo área del terreno" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales3.gif" title="Paso 3: Cálculo área del terreno" data-title="Paso
Actualizar el GIF con la nueva expresión.

Este GIF no requiere mostrar 25 filas de la tabla de atributos. La letra está demasiado pequeña y se dificulta ver lo que se escribe en las ventanas que aparecen en el GIF.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +El diligenciamiento de esta relación se realiza con la herramienta ``Llenar más CCL y menos`` ubicada en la barra de herramientas. Al hacer clic en este botón, emergerá un cuadro de diálogo preguntan
Revisar escritura de "preguntandóte"

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Para verificar el estado de las relaciones creadas previamente, basta con abrir la tabla de atributos de la tabla **Col_masccl**, y en la columna *col_mas* corroborar si los campos están diligenciado
La columna no se llama "col_mas".

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +En primera medida, debes cargar a tu espacio de trabajo la capa **topo_construcciones**, para esto, debes dirigirte al **Navegador**, seleccionar **geopackage -> taller_asistente.gpkg** y arrastrar l
Cambiar geopackage por GeoPackage.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +En primera medida, debes cargar a tu espacio de trabajo la capa **topo_construcciones**, para esto, debes dirigirte al **Navegador**, seleccionar **geopackage -> taller_asistente.gpkg** y arrastrar l
Revisar escritura de "seá"

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +En primera medida, debes cargar a tu espacio de trabajo la capa **topo_construcciones**, para esto, debes dirigirte al **Navegador**, seleccionar **geopackage -> taller_asistente.gpkg** y arrastrar l
Cambiar 
     arrastrar la capa **topo_construcciones** a la interfaz 
por 
     arrastrar la capa **topo_construcciones** al mapa

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +De inmediato, se desplegará la ventana de mapeo de campos, en la cual debes realizar las modificaciones correspondientes hasta obtener un muestreo de campos como el de la siguiente imagen:
Cambiar "un muestreo de campos" por "un mapeo de campos"

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 3: Mapeo de campos" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales13.png" title="Paso 3: Mapeo de campos" data-title="Paso 3: Mapeo de campo
Cuidado con la expresión de áreas en la imagen.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +| area_construccion        | $area        |
Cambiar la expresión del cálculo de áreas.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Se recomienda tener en cuenta los pasos desarrollados en el [paso 4](#paso-4-mapeo-de-campos-punto-lindero) de la sección de punto de lindero, considerando que:
No sirve el enlace interno. Cambiar por:

    #paso-5-dialogo-del-mapeo-de-campos-para-punto-lindero

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +#### Paso 2: Creación de construcción
Cambiar por "Creación de las construcciones"

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Se recomienda tener en cuenta los pasos desarrollados en el [paso 4](#paso-4-mapeo-de-campos-punto-lindero) de la sección de punto de lindero, considerando que:
Es confuso hablar de "Los pasos desarrollados en el paso 4".

Cambiar por: "Se recomienda tener en cuenta el paso 4 de la sección de punto de lindero. Para este caso, debemos asignar los valores de la siguiente manera:" y tener en cuenta para las demás secciones que enlacen el paso 5 de Punto lindero.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Se recomienda tener en cuenta los pasos desarrollados en el [paso 4](#paso-4-mapeo-de-campos-punto-lindero) de la sección de punto de lindero, considerando que:
Ojo: Ya no es el paso 4.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Después de completar dichas modificaciones, puedes emplear la acción del botón ``Ejecutar``, y verificar el mensaje del proceso, luego, puedes **Cerrar** la ventana.
Cambiar por: 

Después de completar dichas modificaciones, haz clic en el botón `Ejecutar`. Cuando el proceso termine, puedes verificar los mensajes de la pestaña Registro y posteriormente cerrar la ventana.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +### Unidades De Construcción
Cambiar por:

     ### Unidades de Construcción

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +#### Paso 2: Creación de unidad de construcción
Cambiar por:

Creación de unidades de construcción

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Después de tener los *t_id* se procede con el proceso de creación de las *Unidades de construcción*, para ello debes dirigirte a **LADM-COL –> Captura Y Estructuración De Datos –> Levantamiento Catas
Cambiar por:

Después de identificar el t_id de la Construcción, se procede a crear las Unidades de construcción. Para ello debes...

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Finalmente, al cerrar el cuadro de diálogo, podrás visualizar un sólido en 2.5D que representa la construcción:
En la imagen no se observa un sólido en 2.5 y si lo hubiese, este no representaría la construcción sino la Unidad de Construcción.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 1: Creación de servidumbre de paso" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales17.gif" title="Paso 1: Creación de servidumbre de paso" da
La animación pequeña y la grande no coinciden.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Una vez que termines la digitalización del polígono se desplegará un formulario, que tiene algunas casillas resaltadas, las cuales indican que deben diligenciarse de forma obligatoria.
Cambiar por:

Una vez que termines la digitalización del polígono, se desplegará un formulario que tiene algunas casillas resaltadas, las cuales deben diligenciarse de forma obligatoria.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 2: Formulario de la servidumbre de paso" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales18.gif" title="Paso 2: Formulario de la servidumbre d
La animación pequeña y la grande no coinciden.

2021-07-01 23:16 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 3: Resultado de la servidumbre de paso" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales22.png" title="Paso 3: Resultado de la servidumbre de
La imagen pequeña y la grande no coinciden.

2021-07-09 23:19 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Se recomienda tener en cuenta los pasos desarrollados en el [paso 4](#paso-4-mapeo-de-campos-punto-lindero) de la sección de punto de lindero, considerando que:
Decidí cambiarlos todos al paso 5, ya que este es el que relaciona como deben ser llenados los mapeos de campos. y dejarlo con el texto que me sugieres en esta parte, gracias

2021-07-09 23:25 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Después de tener los *t_id* se procede con el proceso de creación de las *Unidades de construcción*, para ello debes dirigirte a **LADM-COL –> Captura Y Estructuración De Datos –> Levantamiento Catas
Consideras que debemos mantener t_id y Unidades de construcción con italics ? o mejor sin nada de eso ?

2021-07-09 23:56 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Finalmente, al cerrar el cuadro de diálogo, podrás visualizar un sólido en 2.5D que representa la construcción:
> Muchos comentarios.
> 
> Estas recomendaciones se deben tener en cuenta para las demás subsecciones que se elaboren.

Claro que sí, muchas gracias

2021-07-09 23:57 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<p>Para el caso de <b>area_construccion</b>, se utiliza la expresión <i>$area</i> ya que los datos iniciales no cuentan con información para este campo.</p>
Cambios realizados en el commit 563d3ea.

2021-07-09 23:58 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Una vez que los terrenos han sido creados, es necesario calcular o en su defecto actualizar el área del terreno. Para ello, debes dar clic en el botón `Abrir tabla de atributos` ubicado en la parte s
Tienes razón, cambios realizados en el commit 563d3ea.

2021-07-09 23:58 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +### Servidumbre de paso
Cambios realizados en el commit 563d3ea.

2021-07-09 23:58 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +</ol>
Cambios realizados en el commit 563d3ea.

2021-07-09 23:58 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Posteriormente, das clic en la opción *"Seleccionar todos los linderos"* y luego en el botón `Finalizar`.
Cambios realizados en el commit 563d3ea.

2021-07-09 23:58 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Posteriormente, das clic en la opción *"Seleccionar todos los linderos"* y luego en el botón `Finalizar`.
Cambios realizados en el commit 563d3ea.

2021-07-09 23:59 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +#### Paso 3: Cálculo área del terreno
Cambios realizados en el commit 563d3ea.

2021-07-09 23:59 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Una vez que los terrenos han sido creados, es necesario calcular o en su defecto actualizar el área del terreno. Para ello, debes dar clic en el botón `Abrir tabla de atributos` ubicado en la parte s
Cambios realizados en el commit 563d3ea.

2021-07-09 23:59 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 3: Cálculo área del terreno" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales3.gif" title="Paso 3: Cálculo área del terreno" data-title="Paso
Cambios realizados en el commit 563d3ea.

2021-07-09 23:59 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +El diligenciamiento de esta relación se realiza con la herramienta ``Llenar más CCL y menos`` ubicada en la barra de herramientas. Al hacer clic en este botón, emergerá un cuadro de diálogo preguntan
Cambios realizados en el commit 563d3ea.

2021-07-09 23:59 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Para verificar el estado de las relaciones creadas previamente, basta con abrir la tabla de atributos de la tabla **Col_masccl**, y en la columna *col_mas* corroborar si los campos están diligenciado
Cambios realizados en el commit 563d3ea.

2021-07-09 23:59 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +En primera medida, debes cargar a tu espacio de trabajo la capa **topo_construcciones**, para esto, debes dirigirte al **Navegador**, seleccionar **geopackage -> taller_asistente.gpkg** y arrastrar l
Cambios realizados en el commit 563d3ea.

2021-07-09 23:59 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +En primera medida, debes cargar a tu espacio de trabajo la capa **topo_construcciones**, para esto, debes dirigirte al **Navegador**, seleccionar **geopackage -> taller_asistente.gpkg** y arrastrar l
Cambios realizados en el commit 563d3ea.

2021-07-09 23:59 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +En primera medida, debes cargar a tu espacio de trabajo la capa **topo_construcciones**, para esto, debes dirigirte al **Navegador**, seleccionar **geopackage -> taller_asistente.gpkg** y arrastrar l
Cambios realizados en el commit 563d3ea.

2021-07-09 23:59 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +De inmediato, se desplegará la ventana de mapeo de campos, en la cual debes realizar las modificaciones correspondientes hasta obtener un muestreo de campos como el de la siguiente imagen:
Cambios realizados en el commit 563d3ea.

2021-07-09 23:59 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 3: Mapeo de campos" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales13.png" title="Paso 3: Mapeo de campos" data-title="Paso 3: Mapeo de campo
Cambios realizados en el commit 563d3ea.

2021-07-10 00:00 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +| area_construccion        | $area        |
Cambios realizados en el commit 563d3ea.

2021-07-10 00:00 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Se recomienda tener en cuenta los pasos desarrollados en el [paso 4](#paso-4-mapeo-de-campos-punto-lindero) de la sección de punto de lindero, considerando que:
Cambios realizados en el commit 563d3ea.

2021-07-10 00:00 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +#### Paso 2: Creación de construcción
Cambios realizados en el commit 563d3ea.

2021-07-10 00:00 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Se recomienda tener en cuenta los pasos desarrollados en el [paso 4](#paso-4-mapeo-de-campos-punto-lindero) de la sección de punto de lindero, considerando que:
Cambios realizados en el commit 563d3ea.

2021-07-10 00:00 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Después de completar dichas modificaciones, puedes emplear la acción del botón ``Ejecutar``, y verificar el mensaje del proceso, luego, puedes **Cerrar** la ventana.
Cambios realizados en el commit 563d3ea.

2021-07-10 00:00 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +### Unidades De Construcción
Cambios realizados en el commit 563d3ea.

2021-07-10 00:00 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +#### Paso 2: Creación de unidad de construcción
Cambios realizados en el commit 563d3ea.

2021-07-10 00:01 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Después de tener los *t_id* se procede con el proceso de creación de las *Unidades de construcción*, para ello debes dirigirte a **LADM-COL –> Captura Y Estructuración De Datos –> Levantamiento Catas
Cambios realizados en el commit 563d3ea.

2021-07-10 00:01 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Finalmente, al cerrar el cuadro de diálogo, podrás visualizar un sólido en 2.5D que representa la construcción:
Cambios realizados en el commit 563d3ea.

2021-07-10 00:01 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 1: Creación de servidumbre de paso" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales17.gif" title="Paso 1: Creación de servidumbre de paso" da
Cambios realizados en el commit 563d3ea.

2021-07-10 00:01 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +Una vez que termines la digitalización del polígono se desplegará un formulario, que tiene algunas casillas resaltadas, las cuales indican que deben diligenciarse de forma obligatoria.
Cambios realizados en el commit 563d3ea.

2021-07-10 00:01 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 2: Formulario de la servidumbre de paso" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales18.gif" title="Paso 2: Formulario de la servidumbre d
Cambios realizados en el commit 563d3ea.

2021-07-10 00:01 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 3: Resultado de la servidumbre de paso" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales22.png" title="Paso 3: Resultado de la servidumbre de
Cambios realizados en el commit 563d3ea.

2021-07-14 00:19 UTC, gacarrillor requested changes

2021-07-14 00:19 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
En la animación cap5undespaciales3.gif, actualizar los 4 textos de título a:

Paso 3: Cálculo del área del terreno

2021-07-14 00:19 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
En la animación cap5undespaciales17.gif, actualizar los 4 textos de título a:

Paso 2: Creación de unidades de construcción

2021-07-14 00:19 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
Si es posible, mejorar la animación cap5undespaciales17.gif, es lento y tarda mucho tiempo en la primera parte (mostrando incluso el menú de Administración de datos demasiado tiempo).

2021-07-14 00:19 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
Cambiar:

"Digitaliza el polígono correspondiente, tan pronto termines,"

Por:

"Digitaliza el polígono correspondiente. Tan pronto termines,"

2021-07-14 00:19 UTC, gacarrillor commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 2: Formulario de la Servidumbre de transito" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales18.gif" title="Paso 2: Formulario de la Servidumb
Demasiado pesado este GIF cap5undespaciales18.gif, pesa 18.8MB.

Es bastante lento, especialmente en la captura del polígono. Favor mejorarlo.

2021-07-14 16:41 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
Cambios realizados en el commit c744d62.

2021-07-14 16:41 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
Cambios realizados en el commit c744d62.

2021-07-14 16:41 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
Cambios realizados en el commit c744d62.

2021-07-14 16:41 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
Cambios realizados en el commit c744d62.

2021-07-14 16:41 UTC, jhonalex06 commented on source/tutorial/captura_y_estructuracion_de_datos.md
> +<a class="" data-lightbox="Paso 2: Formulario de la Servidumbre de transito" href="../_static/tutorial/captura_y_estructura_de_datos/cap5undespaciales18.gif" title="Paso 2: Formulario de la Servidumb
Cambios realizados en el commit c744d62.

2021-07-15 23:46 UTC, gacarrillor reviewed
@jhonalex06, no hagas más esto:

![image](https://user-images.githubusercontent.com/652785/125871242-8d4ac325-904c-44e4-a960-419f789f4ca6.png)

En su lugar, haz un `rebase`:

¿Por qué?
Porque el `merge` nos daña el historial de commits. 
El `rebase` mantiene el historial de manera correcta.

Leer:
 + https://roytuts.com/how-to-rebase-feature-branch-with-master-branch-in-git-repository/

2021-07-15 23:48 UTC, merged

2021-07-16 14:21 UTC, jhonalex06 commented
> @jhonalex06, no hagas más esto:
> 
> ![image](https://user-images.githubusercontent.com/652785/125871242-8d4ac325-904c-44e4-a960-419f789f4ca6.png)
> 
> En su lugar, haz un `rebase`:
> 
> ¿Por qué?
> Porque el `merge` nos daña el historial de commits.
> El `rebase` mantiene el historial de manera correcta.
> 
> Leer:
> 
> * https://roytuts.com/how-to-rebase-feature-branch-with-master-branch-in-git-repository/

Uyyyy, listo si señor, lo voy a tener en cuenta

2021-07-22 12:56 UTC, jhonalex06 commented
> > @jhonalex06, no hagas más esto:
> > ![image](https://user-images.githubusercontent.com/652785/125871242-8d4ac325-904c-44e4-a960-419f789f4ca6.png)
> > En su lugar, haz un `rebase`:
> > ¿Por qué?
> > Porque el `merge` nos daña el historial de commits.
> > El `rebase` mantiene el historial de manera correcta.
> > Leer:
> > 
> > * https://roytuts.com/how-to-rebase-feature-branch-with-master-branch-in-git-repository/
> 
> Uyyyy, listo si señor, lo voy a tener en cuenta

Si en este se me fue,  ya lo tengo presente.