Update configuracion.md
SwissTierrasColombia/Asistente-LADM-COL-docs pull request #43
Opened 2021-05-27 03:00 UTC by jonyfido

Actualización sección Roles.

2021-06-03 22:06 UTC, gacarrillor requested changes
Se requieren los cambios sugeridos antes de llevar este PR a la rama máster.

2021-06-03 22:06 UTC, gacarrillor commented on source/configuracion.md
> +|    Básico    |    Perfil de exploración de la herramienta    |Exploración de datos<br>Cargar Capas|
El listado de funcionalidades está incompleto. 

Evaluar si realmente se quieren listar todas las del rol (pueden ser bastantes) o si mejor se retira la columna.

2021-06-03 22:06 UTC, gacarrillor commented on source/configuracion.md
> +| Proveedor de Insumos |  |Corres ETL COBOL, SNC<br>Generar archivo XTF en modelo de Insumos|
¿ "**Corres** ETL COBOL" ? :thinking:

2021-06-03 22:06 UTC, gacarrillor commented on source/configuracion.md
> +| Coordinador de Campo | Perfil encargado de Gestionar los datos de campo |Idem. a Coordinador General menos Validaciones de Calidad|
Las dos descripcionies de los roles de campo son confusas. Se recomienda revisarlas y ajustarlas.

2021-06-03 22:06 UTC, gacarrillor commented on source/configuracion.md
> +<img src="_static/configuracion/toolbar_rol_basico.png" class="align-center" alt="Funcionalidades y toolbar (rol básico)"/>
Las imágenes de menú y toolbar de cada rol deben permitir abrir el dialogo emergente. Ver Guía de Estilo.

2021-06-22 03:48 UTC, jonyfido commented on source/configuracion.md
> +|    Básico    |    Perfil de exploración de la herramienta    |Exploración de datos<br>Cargar Capas|
Listar las funcionalidades mas relevantes le aporta a la documentación, si tiene identificadas algunas funciones faltantes agradezco sus aportes para completarlas o eliminar las que usted considere que no aportan a la documentación.
Gracias

2021-06-22 03:51 UTC, jonyfido commented on source/configuracion.md
> +| Proveedor de Insumos |  |Corres ETL COBOL, SNC<br>Generar archivo XTF en modelo de Insumos|
Se actualiza en 66fd62acf7b505f70d11280eb32d0161408a4d1e

2021-06-22 03:52 UTC, jonyfido commented on source/configuracion.md
> +| Coordinador de Campo | Perfil encargado de Gestionar los datos de campo |Idem. a Coordinador General menos Validaciones de Calidad|
Se actualiza en 66fd62acf7b505f70d11280eb32d0161408a4d1e

2021-06-22 03:52 UTC, jonyfido commented on source/configuracion.md
> +<img src="_static/configuracion/toolbar_rol_basico.png" class="align-center" alt="Funcionalidades y toolbar (rol básico)"/>
Se actualiza en 66fd62acf7b505f70d11280eb32d0161408a4d1e

2021-06-22 20:00 UTC, gacarrillor approved these changes

2021-06-22 20:00 UTC, gacarrillor commented on source/configuracion.md
> +|    Básico    |    Perfil de exploración de la herramienta    |Exploración de datos<br>Cargar Capas|
Listo Jonathan, haremos eso :+1:

2021-06-22 20:29 UTC, gacarrillor commented
Se cierra en favor del PR #51 
Razón: el historial de commits de este PR está estropeado. En particular, el commit https://github.com/SwissTierrasColombia/Asistente-LADM-COL-docs/pull/43/commits/66fd62acf7b505f70d11280eb32d0161408a4d1e devolvió ajustes ya realizados.

2021-06-25 14:06 UTC, closed without merging