Update reglas_de_calidad.md
SwissTierrasColombia/Asistente-LADM-COL-docs pull request #45
Opened 2021-05-28 01:00 UTC by jonyfido

Actualización de reglas de calidad.

2021-06-04 22:55 UTC, gacarrillor requested changes
Se sugiere hablar de los resultados de las reglas de calidad. Esto es:

 + Nuevo grupo en panel de capas (el grupo habilita 2 botones para guardar errores en base de datos GPKG y para guardar un reporte en PDF).
 + Podemos tomar una capa de error y explicar su estructura de campos. Ejemplo: identificador del feature que tiene el error, así como el código y la descripción del error.

2021-06-04 22:55 UTC, gacarrillor commented on source/reglas_de_calidad.md
> ++ Reglas de Consistencia Lógica (22 reglas), verifica las relaciones de los objetos del modelo LADM-COL.
No mencionemos números porque fácilmente se queda desactualizada la documentación con cada nueva regla implementada. Se sugiere quitar la info entre paréntesis de estas últimas 4 líneas.

2021-06-04 22:55 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +Para ejecutar las reglas primero se debe haber cargado previamente las capas a validar como se mostró en la sección [Cargar Capas](cargar_capas.html); se pueden correr las reglas una a una, por grupo
Esto no es cierto. Se pueden ejecutar las reglas de calidad sin haber cargado capas al mapa.

2021-06-04 22:55 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +</div>
No estoy del todo de acuerdo con esta recomendación.

Aquí una pregunta Jonathan. Esto no me ocurre en mi sistema operativo.

Lo podemos discutir por interno.

2021-06-04 22:55 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +El Asistente LADM-COL incluye funcionalidades de revisión y control de calidad de los datos que han sido estructurados en el modelo LADM, para ello le presenta un conjunto de 30 reglas de validación
"conjunto de 30 reglas"

Evitemos números precisos, puesto que la documentación quedaría desactualizada muy fácilmente al agregar o quitar una regla de calidad del plugin.

2021-06-04 22:55 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +El Asistente LADM-COL incluye funcionalidades de revisión y control de calidad de los datos que han sido estructurados en el modelo LADM, para ello le presenta un conjunto de 30 reglas de validación
"le ayudara al usuario a revisar sus datos"

No hablamos de "usted" en la documentación. Ver Guía de estilo.

2021-06-04 22:55 UTC, gacarrillor commented on source/reglas_de_calidad.md
> ++ Reglas para puntos (4 reglas)
Si líneas y polígonos están en mayúsculas, por qué "puntos" no?

2021-06-04 22:55 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +Este grupo de reglas validan en general que los puntos provenientes de un levantamiento predial no se sobrepongan, estén cubiertos por los nodos de un Lindero y los nodos de Terrenos, etc. En el gif
Mejorar redacción de este párrafo, tiene varios fallos.

2021-06-04 22:55 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +
Falso, no hay una regla que valide que los linderos sean más largos de 200 metros.

2021-06-04 22:55 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +Este grupo de reglas validan diferentes características que deben cumplir los elementos con geometría polígono como los terrenos, construcciones, servidumbres y unidades de construcción; al correrlas
Mejorar redacción de este párrafo. Tiene varios fallos.

2021-06-04 22:55 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +Este conjunto de reglas permiten hacer validaciones sobre “reglas de negocio” (definidas por la autoridad catastral o los gestores) que están más asociadas a la vinculación de datos (atributos) con l
Así como se venía haciendo con los demás grupos, sería bueno tener GIF para este grupo.

2021-06-22 04:33 UTC, jonyfido commented on source/reglas_de_calidad.md
> +</div>
Se actualiza en 11e21e23ff08423618049f812e0c3f3afbdbe007
Prefiero colocar la advertencia, por si llegara a ocurrirle a un usuario con un equipo con limitada memoria RAM, y que sepa que es por memoria y no por un fallo en al aplicación, pero si a usted le parece puede quitar esta "Advertencia" si cree que puede generar confusión y no aporta a la documentación.

2021-06-22 04:33 UTC, jonyfido commented on source/reglas_de_calidad.md
> ++ Reglas de Consistencia Lógica (22 reglas), verifica las relaciones de los objetos del modelo LADM-COL.
Se actualiza en 11e21e23ff08423618049f812e0c3f3afbdbe007

2021-06-22 04:33 UTC, jonyfido commented on source/reglas_de_calidad.md
> +Para ejecutar las reglas primero se debe haber cargado previamente las capas a validar como se mostró en la sección [Cargar Capas](cargar_capas.html); se pueden correr las reglas una a una, por grupo
Se corrige en 11e21e23ff08423618049f812e0c3f3afbdbe007

2021-06-22 04:34 UTC, jonyfido commented on source/reglas_de_calidad.md
> +El Asistente LADM-COL incluye funcionalidades de revisión y control de calidad de los datos que han sido estructurados en el modelo LADM, para ello le presenta un conjunto de 30 reglas de validación
Se actualiza en 11e21e23ff08423618049f812e0c3f3afbdbe007

2021-06-22 04:34 UTC, jonyfido commented on source/reglas_de_calidad.md
> ++ Reglas para puntos (4 reglas)
Se corrige en 11e21e23ff08423618049f812e0c3f3afbdbe007

2021-06-22 04:34 UTC, jonyfido commented on source/reglas_de_calidad.md
> +Este grupo de reglas validan en general que los puntos provenientes de un levantamiento predial no se sobrepongan, estén cubiertos por los nodos de un Lindero y los nodos de Terrenos, etc. En el gif
Se ajusta en 11e21e23ff08423618049f812e0c3f3afbdbe007

2021-06-22 04:35 UTC, jonyfido commented on source/reglas_de_calidad.md
> +
Se ajusta y corrige en 11e21e23ff08423618049f812e0c3f3afbdbe007

2021-06-22 04:35 UTC, jonyfido commented on source/reglas_de_calidad.md
> +Este grupo de reglas validan diferentes características que deben cumplir los elementos con geometría polígono como los terrenos, construcciones, servidumbres y unidades de construcción; al correrlas
Se ajusta en 11e21e23ff08423618049f812e0c3f3afbdbe007

2021-06-29 20:44 UTC, jonyfido commented
> Se sugiere hablar de los resultados de las reglas de calidad. Esto es:
> 
> * Nuevo grupo en panel de capas (el grupo habilita 2 botones para guardar errores en base de datos GPKG y para guardar un reporte en PDF).
> * Podemos tomar una capa de error y explicar su estructura de campos. Ejemplo: identificador del feature que tiene el error, así como el código y la descripción del error.

Se ajusta con sugerencias dadas en #45 1b291fb92b96d417e15929abbcb35b08edee82c3

2021-06-29 20:45 UTC, jonyfido commented on source/reglas_de_calidad.md
> +Este conjunto de reglas permiten hacer validaciones sobre “reglas de negocio” (definidas por la autoridad catastral o los gestores) que están más asociadas a la vinculación de datos (atributos) con l
Se incluye en 1b291fb92b96d417e15929abbcb35b08edee82c3

2021-06-30 20:03 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +<a class="" data-lightbox="Conjunto de reglas disponibles" href="_static/reglas_de_calidad/rules_list.png" title="Conjunto de reglas disponibles" data-title="Conjunto de reglas disponibles"><img src=
El archivo está mal enlazado.

2021-06-30 20:03 UTC, gacarrillor commented on source/reglas_de_calidad.md
> ++ Reglas de Consistencia Lógica, verifica las relaciones de los objetos del modelo LADM-COL.
Esta es una buena oportunidad para darle enlaces al usuario para llegar a cada subsección.

2021-06-30 20:03 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +</div>
Listo, si no se quiere discutir por interno, prefiero no mencionar cosas como "bloqueos de la aplicación". Entonces se remueve la advertencia.

Como le comenté, no en todos los sistemas operativos ocurre. 

Por si le interesa, sería más partidario de buscar si hay una manera de evitar dicho diálogo de Windows y contarle al usuario cómo hacer para que Windows no le muestre ese mensaje de bloqueo.

2021-06-30 20:53 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +Este grupo de reglas ayudan a validar que los puntos provenientes de un levantamiento predial no se sobrepongan, ayudan a verificar que los puntos estén cubiertos por los nodos de un lindero y los no
"Este grupo de reglas AYUDA..."

"los nodos de un TERRENO..."

"cómo se EJECUTAN dos de estas reglas..."

2021-06-30 20:53 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +Este grupo de reglas ayudan a validar algunas características que pueden presentar los linderos de un predio; como que estos no se superpongan, que los linderos estén cubiertos por los límites de uno
"Este grupo de reglas AYUDA..."

"cambio de una colindancia, entre OTRAS..." (está hablando de las reglas)

2021-06-30 20:53 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +### Los nodos de Linderos deben estar cubiertos por Putos de Lindero
"por Putos de Lindero"

Favor evitar groserías en la documentación :stuck_out_tongue_closed_eyes:

2021-06-30 20:53 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +### Los nodos de Construcción deben estar cubiertos por Puntos de Levantamiento
¡Esta regla de calidad no existe!

2021-06-30 20:53 UTC, gacarrillor commented on source/reglas_de_calidad.md
> +Una vez se hayan ejecutadas las reglas que se desean revisar sobre los datos que han sido estructurados en el modelo LADM, en el panel de capas de la interfaz se carga una capa para identificar los e
"Una vez se hayan EJECUTADO..."

2021-06-30 20:55 UTC, gacarrillor requested changes
Hice varios ajustes a este PR. Dejo comentarios con observaciones (que ya corregí).

Solo queda pendiente enlazar la imagen `rules_list.png`.

2021-07-01 00:18 UTC, jonyfido commented on source/reglas_de_calidad.md
> +### Los nodos de Linderos deben estar cubiertos por Putos de Lindero
Una disculpa ingeniero :(

2021-07-01 00:36 UTC, jonyfido commented
> Hice varios ajustes a este PR. Dejo comentarios con observaciones (que ya corregí).
> 
> Solo queda pendiente enlazar la imagen `rules_list.png`.

Se realiza corrección a enlace en a5fedb9146b8cbb6cf854b74e6e9095c0f337a9d

2021-07-01 00:43 UTC, gacarrillor approved these changes

2021-07-01 00:44 UTC, merged