Edición de la sección de captura en campo
SwissTierrasColombia/Asistente-LADM-COL-docs pull request #48
Opened 2021-05-28 18:43 UTC by jhonalex06

2021-06-30 04:38 UTC, jonyfido commented
Se actualiza contenido y se deja para revisión en a57a6cb220cd2a2d0ea37bad6a0792e97dbbcc3d

2021-07-01 21:30 UTC, gacarrillor commented
Compañeros, no podemos subir GIFs de más de 60MB a la documentación. Es demasiado.
Hay 2 GIFs que pesan más de 60MB en este PR.

2021-07-01 21:47 UTC, jhonalex06 commented
> Compañeros, no podemos subir GIFs de más de 60MB a la documentación. Es demasiado.
> Hay 2 GIFs que pesan más de 60MB en este PR. Los podemos optimizar (esto es, bajarles considerablemente el tamaño).

Listo, yo los edito, para bajarle la calidad

2021-07-19 21:12 UTC, gacarrillor requested changes
Muy bueno compañeros @jhonalex06 y @jonyfido!

 + [x] Se hizo un trabajo muy bueno al optimizar el tamaño de los GIFs. Sin embargo quería preguntarles si podían examinar esta herramienta, y en caso de tener resultados aceptables (calidad vs. tamaño), utilizarla para los GIFs de esta sección: https://gifcompressor.com/

2021-07-19 21:12 UTC, gacarrillor commented on source/captura_de_datos_en_campo.md
> +8. ETL de Modelo de captura en campo a Modelo de aplicación Lev.Catastral
Las tablas de contenido (ToC) le ayudan mucho al lector a acceder al numeral que quiere consultar.

¿Podemos darle enlaces a cada ítem de esta ToC?

2021-07-19 21:12 UTC, gacarrillor commented on source/captura_de_datos_en_campo.md
> +<p>El reconocedor antes de ir a campo debe instalar y configurar en su dispositivo la última versión de <i>QField</i> para poder cargar y vizualizar correctamente los proyectos entregados por el coor
El enlace a la documentación externa de QField LADM-COL debe abrir en una pestaña nueva.

2021-07-19 21:12 UTC, gacarrillor commented on source/captura_de_datos_en_campo.md
> +<a class="" data-lightbox="Asignar predios Coord.Campo_4" href="_static/captura_de_datos_en_campo/9_Coor_campo_asignacion_6.gif" title="Asignar predios Coord.Campo_4" data-title="Asignar predios Coor
Definir bien los títulos de las animaciones/imágenes. 10 animaciones tienen el mismo título "Asignar predios Coord.Campo_4". En principio ningún título debería repetirse.

2021-07-22 12:58 UTC, jhonalex06 commented
> Muy bueno compañeros @jhonalex06 y @jonyfido!
> 
> * [ ]  Se hizo un trabajo muy bueno al optimizar el tamaño de los GIFs. Sin embargo quería preguntarles si podían examinar esta herramienta, y en caso de tener resultados aceptables (calidad vs. tamaño), utilizarla para los GIFs de esta sección: https://gifcompressor.com/

Listo, yo la reviso a ver que resultado nos otorga, gracias

2021-07-23 20:04 UTC, jhonalex06 commented
> Muy bueno compañeros @jhonalex06 y @jonyfido!
> 
> * [x]  Se hizo un trabajo muy bueno al optimizar el tamaño de los GIFs. Sin embargo quería preguntarles si podían examinar esta herramienta, y en caso de tener resultados aceptables (calidad vs. tamaño), utilizarla para los GIFs de esta sección: https://gifcompressor.com/

Muy buena herramienta, gracias, la utilizé para bajarle el peso a los GIF en el commit 
2267a39.

2021-07-27 03:22 UTC, jhonalex06 commented on source/captura_de_datos_en_campo.md
> +8. ETL de Modelo de captura en campo a Modelo de aplicación Lev.Catastral
Le agregué link a cada item, pero quedarían faltando los de los ETLs, para cuando se desarrolle su documentación, los cambios estan en 719273b.

2021-07-27 03:22 UTC, jhonalex06 commented on source/captura_de_datos_en_campo.md
> +<p>El reconocedor antes de ir a campo debe instalar y configurar en su dispositivo la última versión de <i>QField</i> para poder cargar y vizualizar correctamente los proyectos entregados por el coor
Solucionado en 719273b.

2021-07-28 20:08 UTC, jonyfido commented on source/captura_de_datos_en_campo.md
> +<a class="" data-lightbox="Asignar predios Coord.Campo_4" href="_static/captura_de_datos_en_campo/9_Coor_campo_asignacion_6.gif" title="Asignar predios Coord.Campo_4" data-title="Asignar predios Coor
Solucionado en 82d367caa1376ef4cf270d1694ecf52cbd15833b

2021-07-28 23:00 UTC, gacarrillor approved these changes
A tener en cuenta:

 + Se habla mucho de "Perfiles", sin embargo para el Asistente LADM-COL, siempre se manejarán como "Roles".

2021-07-29 00:53 UTC, merged