Actualización del modulo de reportes
SwissTierrasColombia/Asistente-LADM-COL-docs pull request #54
Opened 2021-07-01 14:22 UTC by lacardonap

Se actualiza la documentación y gifs del modulo de reportes.

2021-07-02 15:52 UTC, gacarrillor requested changes
Reducir el tamaño de los GIFs pues están demasiado pesados. Por ejemplo, reducir la resolución de la pantalla, e intentar comprimir el GIF antes de subirlo.

Para el GIF del reporte ANT se sugiere menos introducción para recortar la duración del GIF.

2021-07-02 15:52 UTC, gacarrillor commented on source/reportes.md
> +El Asistente LADM-COL permite generar reportes de forma masiva y de forma automatizada a partir de los datos que fueron recolectados del levantamiento catastral, para tener acceso a esta funcionalida
Cambiar:
    levantamiento catastral, para
por:
    levantamiento catastral. Para

2021-07-02 15:52 UTC, gacarrillor commented on source/reportes.md
> +El Asistente LADM-COL permite generar reportes de forma masiva y de forma automatizada a partir de los datos que fueron recolectados del levantamiento catastral, para tener acceso a esta funcionalida
Cambiar:
"a esta funcionalidad deberá haber seleccionado el rol de usuario y luego ir al menú"
por:
"a esta funcionalidad debes ir al menú"

2021-07-02 15:52 UTC, gacarrillor commented on source/reportes.md
> +4. Se desplega una ventana de dialogo y se debe diligenciar los campos solicitados y luego dar clic en el botón Generarar.
Cambiar:
"Se desplega una ventana de dialogo y se debe diligenciar los campos solicitados y luego dar clic en el botón Generarar."
Por:
"Se despliega una ventana de dialogo en la cual se deben diligenciar los campos solicitados y luego dar clic en el botón Generar."

2021-07-02 15:52 UTC, gacarrillor commented on source/reportes.md
> +   - **Zona**: Permite seleccionar la zona donde estan ubicados los datos. De acuerdo el apartado 7.3 de la resolución 388 de 2020 del IGAC, el área para predios en el suelo urbano se expresa en metr
Cambiar:
"(m<sup>2</sup> )"
por:
"(m<sup>2</sup>)"

2021-07-02 15:52 UTC, gacarrillor commented on source/reportes.md
> +   - **Elaboró**: Permite diligenciar el nombre completo y su matrícula profesional de la persona que elaboró el reporte.
Cambiar:
"Permite diligenciar el nombre completo y su matrícula profesional de la persona que elaboró el reporte."
Por:
"Permite diligenciar el nombre completo y matrícula profesional de la persona que elaboró el reporte."

Aplicar esta observación en el resto de campos.

2021-07-02 15:52 UTC, gacarrillor commented on source/reportes.md
> +   - **Mapa base**: Permite seleccionar un mapa WMS, el cual será utilizado como mapa base en el mapa de localización general presentado en el reporte.
Cambiar:
"el cual será utilizado como mapa base en el mapa de localización general presentado en el reporte."
Por:
"el cual servirá como mapa base en la localización general del reporte."

2021-07-02 15:52 UTC, gacarrillor commented on source/reportes.md
> +</div>
¿Sin Cartografía Catastral no se puede generar el reporte ANT?

2021-07-02 17:26 UTC, lacardonap commented on source/reportes.md
> +El Asistente LADM-COL permite generar reportes de forma masiva y de forma automatizada a partir de los datos que fueron recolectados del levantamiento catastral, para tener acceso a esta funcionalida
Gracias por la corrección. Ajuste realizado en el commit e2da978

2021-07-02 17:26 UTC, lacardonap commented on source/reportes.md
> +El Asistente LADM-COL permite generar reportes de forma masiva y de forma automatizada a partir de los datos que fueron recolectados del levantamiento catastral, para tener acceso a esta funcionalida
Gracias por la corrección. Ajuste realizado en el commit e2da978

2021-07-02 17:26 UTC, lacardonap commented on source/reportes.md
> +4. Se desplega una ventana de dialogo y se debe diligenciar los campos solicitados y luego dar clic en el botón Generarar.
Gracias por la corrección. Ajuste realizado en el commit e2da978

2021-07-02 17:26 UTC, lacardonap commented on source/reportes.md
> +   - **Zona**: Permite seleccionar la zona donde estan ubicados los datos. De acuerdo el apartado 7.3 de la resolución 388 de 2020 del IGAC, el área para predios en el suelo urbano se expresa en metr
Gracias por la corrección. Ajuste realizado en el commit e2da978

2021-07-02 17:26 UTC, lacardonap commented on source/reportes.md
> +   - **Elaboró**: Permite diligenciar el nombre completo y su matrícula profesional de la persona que elaboró el reporte.
Gracias por la corrección. Ajuste realizado en el commit e2da978

2021-07-02 17:27 UTC, lacardonap commented on source/reportes.md
> +   - **Mapa base**: Permite seleccionar un mapa WMS, el cual será utilizado como mapa base en el mapa de localización general presentado en el reporte.
Gracias por la corrección. Ajuste realizado en el commit e2da978

2021-07-02 17:31 UTC, lacardonap commented on source/reportes.md
> +</div>
No es posible generar el reporte de la ANT si la base de datos no tiene el submodelo de Cartografía Catastral v1.0. El reporte de la ANT muestra el límite del corregimiento, centro poblado, vías, municipio, departamento en el mapa y dicha información se obtiene del submodelo de Cartografía Catastral.


![image](https://user-images.githubusercontent.com/8827336/124309954-2248aa00-db31-11eb-8c29-927c04a37d12.png)

2021-07-02 17:32 UTC, lacardonap commented
El tamaño de los gif fueron reducidos. Gracias por la sugerencia. Todos los cambios solicitados fueron realizados.

2021-07-09 21:26 UTC, gacarrillor approved these changes

2021-07-09 21:26 UTC, merged