Actualización identificación de novedades
SwissTierrasColombia/Asistente-LADM-COL-docs pull request #62
Opened 2021-07-30 04:20 UTC by jonyfido

Se agrega contenido a la sección.

2021-07-30 06:01 UTC, jonyfido commented
@jhonalex06 Pendiente de incluir GIFs

2021-08-17 20:07 UTC, gacarrillor requested changes
He dejado algunos comentarios generales. 

Aún no he hecho una revisión de cómo luce este PR ya desplegado. Favor hacer los ajustes y luego procedo con una revisión más en detalle.

2021-08-17 20:07 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +</div>
Podríamos verificar eso?
El usuario no debería tener que revisar nada. En caso de que esté ocurriendo así, podemos abrir un issue para que el Asistente LADM-COL haga ese chequeo automáticamente.

2021-08-17 20:07 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +<p>Para poder importar el conjunto de datos “Insumos” es necesario que el nuevo esquema tenga la estructura del modelo LADM-COL, para ello ver la sección <a href="https://swisstierrascolombia.github.
Creo que quiere decir: "es necesario que el nuevo esquema tenga la estructura del submodelo de Insumos Catastrales", no les parece?

2021-08-17 20:07 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +</div>
Este "Importante" me parece que está bien, pero debería ir justo antes de la subsección "Configuración identificación de novedades".

2021-08-17 20:07 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +El formulario presenta cuatro columnas en donde se muestra el atributo por el cual se hace la comparación, el dato de la fuente oficial (insumos), el dato del levantamiento catastral y el estado, est
La parte que dice: 

"Es de notar que en la parte superior de la tabla de resultados se encuentra una caja de selección (*checkbox*) que se encuentra activa por defecto y permite ver gráficamente todos los predios de la fuente de datos en un color diferente al seleccionado y sí se deselecciona solo muestra el predio objeto de la consulta en la vista de mapa."

amerita ser un TIP para el usuario.

2021-08-17 20:07 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +Al ejecutar esta funcionalidad se carga un reporte en panel de resultados en la parte derecha de la vista mapa en donde se muestra un contador con los cambios identificados en los dos conjuntos de da
Me parece bien el comentarle al usuario que la herramienta de comparación gráfica solo se activa en cierta vista de resultados. De hecho, podríamos contarle en cuáles tipos de novedades va a poder usarla, pues no es en todas, y eso vendría bien en una caja de mensajes, bien sea TIP o IMPORTANTE.

Adicionalmente, podemos omitir el nombre de la herramienta `(*MapSwipe Tool*)`, puesto que es un detalle técnico que no es necesario que el usuario conozca.

2021-08-17 20:07 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +1-    Vaya al módulo del Asistente LADM-COL en la parte superior del programa QGIS y seleccione el menú “Identificación de novedades” y luego de clic en “Configurar identificación de novedades” como
"Vaya al módulo"

No usteamos en la documentación del Asistente LADM-COL. Favor revisar eso en otras partes de este PR.

2021-11-19 05:18 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +1-    Vaya al módulo del Asistente LADM-COL en la parte superior del programa QGIS y seleccione el menú “Identificación de novedades” y luego de clic en “Configurar identificación de novedades” como
Ok corregido.

2021-11-19 05:31 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +<p>Para poder importar el conjunto de datos “Insumos” es necesario que el nuevo esquema tenga la estructura del modelo LADM-COL, para ello ver la sección <a href="https://swisstierrascolombia.github.
Totalmente de acuerdo.

2021-11-19 05:35 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +</div>
Se elimina Advertencia.

2021-11-19 05:37 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +</div>
OK

2021-11-19 05:42 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +El formulario presenta cuatro columnas en donde se muestra el atributo por el cual se hace la comparación, el dato de la fuente oficial (insumos), el dato del levantamiento catastral y el estado, est
Done!

2021-11-19 05:49 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +Al ejecutar esta funcionalidad se carga un reporte en panel de resultados en la parte derecha de la vista mapa en donde se muestra un contador con los cambios identificados en los dos conjuntos de da
OK.

2021-11-20 03:27 UTC, gacarrillor reviewed
Yo revisaré y ajustaré los cambios.

No espero otras modificaciones de su parte, @jonyfido.

2021-11-20 03:27 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +Al ejecutar esta funcionalidad se carga un reporte en panel de resultados en la parte derecha de la vista mapa en donde se muestra un contador con los cambios identificados en los dos conjuntos de da
Redacción...

2021-11-20 03:27 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +<p>Es de notar que en la parte superior de la tabla de resultados se encuentra una caja de selección (*checkbox*) que se encuentra activa por defecto y permite ver gráficamente todos los predios de l
Redacción...

2021-11-20 03:27 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +2-    Ahora se procede a importar los datos desde el archivo XTF del conjunto de datos, para ello se puede ir al módulo del Asistente LADM-COL en la parte superior del programa QGIS y seleccionar el
Muy denso...

2021-11-20 03:27 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +1-    Puedes ir al módulo del Asistente LADM-COL en la parte superior del programa QGIS y seleccione el menú “Identificación de novedades” y luego dar clic en “Configurar identificación de novedades”
Verificar si sirve este enlace

2021-11-20 03:27 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +El Asistente LADM-COL permite realizar el despliegue y comparación de la información producto del Levantamiento Catastral frente a la información oficial de la autoridad catastral, es de mucha utilid
Redacción...

2021-11-20 03:27 UTC, gacarrillor commented on source/identificacion_de_novedades.md
> +<p>Para poder utilizar la funcionalidad de novedades se necesita tener configurado y activa las dos fuentes de datos “Levantamiento Catastral” e “insumos” para realizar la comparación de datos predia
¿ "configurado y activa las dos fuentes de datos" ?

¿Masculino/Femenino/plural/singular?

2021-11-24 06:51 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +El Asistente LADM-COL permite realizar el despliegue y comparación de la información producto del Levantamiento Catastral frente a la información oficial de la autoridad catastral, es de mucha utilid
Corregido.

2021-11-24 06:54 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +<p>Para poder utilizar la funcionalidad de novedades se necesita tener configurado y activa las dos fuentes de datos “Levantamiento Catastral” e “insumos” para realizar la comparación de datos predia
Corregido.

2021-11-24 07:05 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +1-    Puedes ir al módulo del Asistente LADM-COL en la parte superior del programa QGIS y seleccione el menú “Identificación de novedades” y luego dar clic en “Configurar identificación de novedades”
Verificado.

2021-11-24 07:14 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +2-    Ahora se procede a importar los datos desde el archivo XTF del conjunto de datos, para ello se puede ir al módulo del Asistente LADM-COL en la parte superior del programa QGIS y seleccionar el
Ajustado.

2021-11-24 07:18 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +<p>Es de notar que en la parte superior de la tabla de resultados se encuentra una caja de selección (*checkbox*) que se encuentra activa por defecto y permite ver gráficamente todos los predios de l
Ajustado.

2021-11-24 07:21 UTC, jonyfido commented on source/identificacion_de_novedades.md
> +Al ejecutar esta funcionalidad se carga un reporte en panel de resultados en la parte derecha de la vista mapa en donde se muestra un contador con los cambios identificados en los dos conjuntos de da
Ajustado.

2021-11-24 07:26 UTC, jonyfido commented
Se revisa y se ajusta lo solicitado.

2021-12-07 01:57 UTC, gacarrillor approved these changes
Haré retoques finales antes del merge.

Gracias @jonyfido

2021-12-14 20:46 UTC, merged