Actualización Consulta de datos
SwissTierrasColombia/Asistente-LADM-COL-docs pull request #63
Opened 2021-07-30 06:00 UTC by jonyfido

Se agrega contenido e imagenes.

2021-07-30 06:01 UTC, jonyfido commented
@jhonalex06 Pendiente de incluir GIFs

2021-08-07 03:13 UTC, jhonalex06 commented
> @jhonalex06 Pendiente de incluir GIFs

Listo, GIFs incluidos en el commit 89b6487

2021-08-17 20:24 UTC, gacarrillor requested changes

2021-08-17 20:24 UTC, gacarrillor commented on source/consulta_de_datos.md
> +Una vez se tengan cargadas las capas y tablas de la base de datos en el panel de capas de QGIS se puede acceder al menú “Consultar datos”, para acceder a este menú vaya al módulo del Asistente LADM-C
`Una vez se tengan cargadas las capas y tablas de la base de datos en el panel de capas de QGIS se puede acceder al menú “Consultar datos”,`

Esto no es cierto, podemos usar el módulo de Consultas incluso si el proyecto de QGIS está vacío. Como da lo mismo si hay o no capas cargadas, no veo la necesidad de mencionarlo, pues en realidad decir que "solo sirve de una forma, pero si no hay capas también sirve..." solo ayuda a confundir un poco al usuario.

2021-08-17 20:24 UTC, gacarrillor commented on source/consulta_de_datos.md
> +<p>En caso de no cargar los datos automáticamente se pueden agregar los datos desde el menú “Cargar capas” como se explicó en la sección</p>
Favor remover el TIP, puesto que no hay ningún caso en el que "no carguen los datos automáticamente" al usar el módulo de consultas.

2021-08-17 20:24 UTC, gacarrillor commented on source/consulta_de_datos.md
> +Se utiliza el identificador para seleccionar algún elemento de la capa terreno para su consulta.
cambiar:

`Se utiliza el identificador para seleccionar...`

por:

`Se utiliza la herramienta "identificador espacial" para seleccionar...`

2021-08-17 20:24 UTC, gacarrillor commented on source/consulta_de_datos.md
> +<a class="" data-lightbox="Consulta jurídica" href="_static/consulta_de_datos/Consulta_juridica.png" title="Consulta jurídica" data-title="Consulta jurídica"><img src="_static/consulta_de_datos/Consu
Hubiese sido muy bueno haber desplegado el ítem "Derechos (2)", para que se viera info como el tipo de derecho, los interesados, etc.

2021-08-17 20:24 UTC, gacarrillor commented on source/consulta_de_datos.md
> +* Abrir formulario para predio: Muestra el formulario del (t_id) seleccionado en donde se visualiza todos los datos guardados; permite editarlos si la capa se encuentra en modo de edición, como se mu
"permite editarlos si la capa se encuentra en modo de edición, como se muestra en la imagen."

Esta frase confunde porque en la imagen no se muestra el modo de edición activo. O bien se ajusta la animación, o se restructura la descripción de "Abrir formulario para predio".

2021-11-19 04:08 UTC, jonyfido commented on source/consulta_de_datos.md
> +Una vez se tengan cargadas las capas y tablas de la base de datos en el panel de capas de QGIS se puede acceder al menú “Consultar datos”, para acceder a este menú vaya al módulo del Asistente LADM-C
OK

2021-11-19 04:10 UTC, jonyfido commented on source/consulta_de_datos.md
> +<p>En caso de no cargar los datos automáticamente se pueden agregar los datos desde el menú “Cargar capas” como se explicó en la sección</p>
OK

2021-11-19 04:12 UTC, jonyfido commented on source/consulta_de_datos.md
> +Se utiliza el identificador para seleccionar algún elemento de la capa terreno para su consulta.
OK

2021-11-19 04:21 UTC, jonyfido commented on source/consulta_de_datos.md
> +<a class="" data-lightbox="Consulta jurídica" href="_static/consulta_de_datos/Consulta_juridica.png" title="Consulta jurídica" data-title="Consulta jurídica"><img src="_static/consulta_de_datos/Consu
Se tendrá en cuenta para la siguiente iteración.

2021-11-19 04:24 UTC, jonyfido commented on source/consulta_de_datos.md
> +* Abrir formulario para predio: Muestra el formulario del (t_id) seleccionado en donde se visualiza todos los datos guardados; permite editarlos si la capa se encuentra en modo de edición, como se mu
OK

2021-11-19 04:29 UTC, jonyfido commented
Se actualiza el archivo MD con los cambios sugeridos.

2021-11-19 21:37 UTC, gacarrillor reviewed
Se realizaron varios ajustes al PR, con ello se da por cerrado.

2021-11-19 21:37 UTC, merged